### ISSUE TITLE
[FR] (f3D-принтер Creality Ender 3 V2+BIGTREETECH-TFT35-V3.0+skr mini e3 v3.0+BTT SFS V2.0+Creality CRtouch (3D-Touch, BLTouch)+Sprite Extruder Proeature summary)

### ISSUE THREAD

**Issue by roman78-r** [haqbany/SKR-Mini-E3-3.0#1]
### Is your feature request related to a problem? Please describe.

I need a working firmware for my configuration, both the board and the display  3D-принтер Creality Ender 3 V2+BIGTREETECH-TFT35-V3.0+skr mini e3 v3.0+BTT SFS V2.0+Creality CRtouch (3D-Touch, BLTouch)+Sprite Extruder Pro

### Are you looking for hardware support?

3D-принтер Creality Ender 3 V2+BIGTREETECH-TFT35-V3.0+skr mini e3 v3.0+BTT SFS V2.0+Creality CRtouch (3D-Touch, BLTouch)+Sprite Extruder Pro

### Describe the feature you want

combine all the parts into one working printer

### Additional context

maybe someone has a ready-made solution for such a configuration?
I can't do it myself, I'm far from programming

**Comment by haqbany** [comment]
Have you tested my firmware yet? And what errors do you have exactly
because my firmware and the screen are compatible with your configuration
the only difference is the Sprite Extruder which can be
configured from the screen E-Step

**Comment by roman78-r** [comment]
I can't do it myself, I'm far from programming?

**Comment by roman78-r** [comment]
can I upload a video here?

**Comment by roman78-r** [comment]
I'm not like I can't set up all the devices in one system

**Comment by roman78-r** [comment]
I can't insert a large video file, I can send it by e-mail

**Comment by haqbany** [comment]
Send the video to ***@***.***

**Comment by roman78-r** [comment]
roma.78.78@INBOX.RU MY MAIL, 
YOURS IS NOT SHOWN( ***@***.***> )

**Comment by roman78-r** [comment]
haqbany@gmail.com      I AM SENDING IT TO THIS ADDRESS

**Comment by haqbany** [comment]
[Marlin_Ender_3v2_Sprite_Extruder-Pro_bltouch.zip](https://github.com/user-attachments/files/16046102/Marlin_Ender_3v2_Sprite_Extruder-Pro_bltouch.zip)

**Comment by haqbany** [comment]
[firmware.bin.zip](https://github.com/user-attachments/files/16087637/firmware.bin.zip)
 you must unzip the file and copay the firmware.bin in the SD card
this is revert e stepper " INVERT_E0_DIR true //RH "

**Comment by haqbany** [comment]
[firmware.bin.zip](https://github.com/user-attachments/files/16087671/firmware.bin.zip)
 you must unzip the file and copay the firmware.bin in the SD card

this normal e stepper " INVERT_E0_DIR false //RH "

**Comment by roman78-r** [comment]
thanks a lot, everything works fine, except for the wire breakage sensor, I am very grateful

**Comment by roman78-r** [comment]
is the hardware configuration like that yes

**Comment by ret-medic** [comment]
Anyone have the firmware for a Ender 3 Max 300 mm x 300 mm x 340 mm, SKR mini 3 v3 Motherboard, Sprite Pro 300 degrees extruder, CR Touch, dual Z rods (Y power lead, 2 motors into 1), bigtreetech relay v1.2, BigTreeTech Tft35 E3?v3.0.1 touch screen display and Creality smart runout sensor. can be reached at Amrmedic@Hotmail.com
