### ISSUE TITLE
Does this work on Ender 3 v1? 

### ISSUE THREAD

**Issue by jmhpena** [haqbany/SKR-Mini-E3-3.0#2]
### Is your feature request related to a problem? Please describe.

I installed the BIGTREETECH-SKR-mini-E3 on my ender 3 v1(2018) that I recently purchased because the original board wasn't compatible with some of the upgrades that I wanted to make. However, I would like to install a cr touch for auto bed leveling, however, the v5 version on https://github.com/haqbany/Bigtreetouch-SKR-Mini-E3V3.0/releases states that it is made for the ender 3 v2 and Ender 3v2 Neo. I would like to know if this would also work on the ender 3 v1, and if not, do you have another version that will?

### Describe the feature you want

ender 3 v1(2018) compatibility

**Comment by haqbany** [comment]
The firmware you mentioned for the BIGTREETECH-SKR-mini-E3 should generally be compatible with the Ender 3 v1 as long as the motherboard version is the same (Bigtreetouch-SKR-Mini-E3V3.0). The firmware primarily targets the motherboard, so the specific model of the Ender 3 (v1, v2, or v2 Neo) should not matter significantly. You might need to adjust some configurations related to the screen and other peripherals, but these can typically be handled within the firmware settings or through slight modifications.

If you face specific issues during the installation or configuration, feel free to share them, and I can help you troubleshoot or adjust the firmware accordingly.

**Comment by haqbany** [comment]
The firmware you mentioned for the BIGTREETECH-SKR-mini-E3 should generally be compatible with the Ender 3 v1 as long as the motherboard version is the same (Bigtreetouch-SKR-Mini-E3V3.0). The firmware primarily targets the motherboard, so the specific model of the Ender 3 (v1, v2, or v2 Neo) should not matter significantly. You might need to adjust some configurations related to the screen and other peripherals, but these can typically be handled within the firmware settings or through slight modifications.

If you face specific issues during the installation or configuration, feel free to share them, and I can help you troubleshoot or adjust the firmware accordingly.

**Comment by jmhpena** [comment]
Thank you. I did install the firmware, after you confirmed, however, now, for some reason, something seems to be wrong. After installing the firmware, I installed the CR touch, which is why I installed the new board and firmware to begin with. After installing the CR touch, for some reason, I now have two issues. The first is that the bed leveling seems off. After it performs an auto bed leveling, when I start a print, the print starts with the Z axis far too high, by almost 10mm. Secondly, after installing, for some reason, the printer is no longer feeding filament. It will expel filament, but it won't feed it. Do you know what could be causing this?

**Comment by haqbany** [comment]
Hi no worries,  please send me pictures or your printer in tell me exactly
what upgrade in it . We can modify the firmware to fit your printer.  Is
the lid screen works ? If yes what time of screen it's?

**Comment by jmhpena** [comment]
Thank you. I have the Ender 3(2018) with an Bigtreetech-SKR-mini-E3 v3, the dual z-axis upgrade which was also installed today, and the CR touch. I only have the stock screen at this time. I have attached the images of the printer as requested. 
![20240715_142517](https://github.com/user-attachments/assets/71f0103a-33aa-4f8e-ab1b-dd47117c6fdc)
![20240715_142524](https://github.com/user-attachments/assets/5a62e895-ec60-42b7-9a23-5a9d1c1e5344)

**Comment by jmhpena** [comment]
I am planning to put a direct drive extruder and an all metal hot end on it in the future, however, I have to wait until I am able to.

**Comment by haqbany** [comment]
before we do any thing please go here https://github.com/haqbany/SKR-Mini-E3-3.0/issues/1
and try this 2 firmware   see if any work fine and report back .
<img width="1231" alt="Screenshot 2024-07-15 at 9 35 53 PM" src="https://github.com/user-attachments/assets/d7bb0db8-8bb3-49c0-8af1-5fb9f0e38bc3">

**Comment by jmhpena** [comment]
I ran the first one and currently have a calibration cube printing. I am going to see how it turns out, however, the good news is that it is currently extruding properly and seems to be properly leveled. I will let you know how it looks when complete. Thank you!

**Comment by jmhpena** [comment]
Ok. So it seems like that firmware change has done the trick. Thank you very much. 

I do have another non-related question however, that maybe you could help me with. Prior to the upgrades, I was able to print the calibration cube in about 38 minutes. However, now, it seems to be taking almost double that amount of time. The first was a failure, as it lost adhesion to the bed, but the second is only about a quarter of the way after 16 minutes. Do you know what could be causing this?

**Comment by haqbany** [comment]
Great to know! The firmware I use is designed to work with:

	•	SKR Mini E3 v3.0
	•	CR Touch (3D-Touch, BLTouch)
	•	[Sprite Extruder Pro (recommended by me as a good choice)
	•	Magnetic bed  (recommended by me as a good choice)

I would not recommend the BIGTREETECH-TFT35-V3.0 screen due to lack of updates.

Regarding speed settings, it’s crucial to adjust them in your slicer software. At the moment, I recommend using OrcaSlicer as it is currently a top choice.

**Comment by haqbany** [comment]
By the way, my service is completely free for the first time, including all firmware releases. In the future, I offer a subscription where you’ll receive 4 tokens for $60 USD. These tokens can be used for custom software, modifications, error-solving, and any assistance you need with your 3D printer, including Marlin and Klipper. Tokens expire within 6 months. If you’re interested in this option, please let me know!

Wish you happy printing!
